version: "3"

services:
  db:
    image: mysql:latest
    container_name: "BikePartsInc2"
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: Tjugo100